ruby_version:
 SPLIT:
   - 'ruby-1.9.3-p545'
   - 'ruby-2.1.5'
   - 'ruby-2.2.2'
bundler_version: 1.3.5
test_pattern:
  - features/*.feature
  - spec/**_spec.rb
test_exclude_pattern:
  - spec/agent_spec.rb
tests:
  - bundle exec rspec spec/agent_spec.rb
cache:
  per_profile: true
  key_paths:
    - Gemfile
    - Gemfile.lock
    - solano.gemspec
    - lib/solano/version.rb
