ruby_version: 'ruby-1.9.3-p545'
bundler_version: 1.3.5
test_pattern:
  - features/*.feature
  - spec/**_spec.rb
test_exclude_pattern:
  - spec/agent_spec.rb
tests:
  - bundle exec rspec spec/agent_spec.rb
cache:
  key_paths:
    - Gemfile
    - Gemfile.lock
    - solano.gemspec
    - lib/solano/version.rb
